title: "Tarush's Hub"
description: "Home for my writing, wiki, and work"
url: "https://tarushsinha.github.io"
baseurl: ""

remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-remote-theme