title: "Tarush's Hub"
description: "Home for my writing, wiki, and work"
url: "https://tarushsinha.github.io"
baseurl: ""

read_time: true
words_per_minute: 200

remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-remote-theme

collections:
  textposts:
    output: true
    permalink: /wiki/textposts/:name/
  podcasts:
    output: true
    permalink: /wiki/podcasts/:name/
  articles:
    output: true
    permalink: /wiki/articles/:name/